# Generated by Django 4.0.1 on 2022-05-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='thumbnailUrl',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='url',
            new_name='name',
        ),
    ]
